# More info at https://github.com/guard/guard#readme

guard :shell do
  watch(%r{^.+\.py$$}) { `ctags -R` }
end

guard 'livereload' do
  watch(%r{${name}/templates/.*}) do |m|
    Notifier.notify(m[0], :title => 'livereload')
    m
  end

  watch(%r{${name}/assets/javascripts/.*}) do |m|
    Notifier.notify(m[0], :title => 'livereload')
    m
  end

  watch(%r{${name}/assets/stylesheets/(?!\.sass-cache).*}) do |m|
    Notifier.notify(m[0], :title => 'livereload')
    m
  end
end
