# More info at https://github.com/guard/guard#readme

guard :shell do
  watch(%r{^.+\.py$$}) { `ctags -R` }
end

guard 'livereload' do
  watch(%r{${project_name}/templates})
  watch(%r{${project_name}/static/(.+\.(css|js|html)).*}) { |m| "/static/#{m[1]}" }
end
