# More info at https://github.com/guard/guard#readme

guard :shell do
  watch(%r{^.+\.py$$}) { `ctags -R` }
end

guard 'livereload' do
  watch(%r{${name}/templates}) do |m|
    Notifier.notify(m[0], :title => 'livereload')
    m
  end

  watch(%r{${name}/static/(.+\.(css|js)).*}) do |m|
    Notifier.notify(m[1], :title => 'livereload')
    "/static/#{m[1]}"
  end
end
