from __future__ import print_function

from collections import OrderedDict
from getpass import getpass
from os import linesep
from os.path import expanduser, join
from string import Template

from django.utils.crypto import get_random_string

from fabric.api import env, task
from fabric.colors import green
from fabric.utils import apply_lcwd

from . import PACKAGE_ROOT, PROJECT_ROOT, VIRTUAL_ENV


LOCAL_SETTINGS = join(PROJECT_ROOT, 'settings.py')


def render_template(filename, context=None):
    filename = apply_lcwd(filename, env)
    with open(expanduser(filename)) as inputfile:
        text = Template(inputfile.read())
    return text.substitute(context or {})


def write_settings(settings_file, target, settings):
    with open(settings_file, 'w+') as of:
        print('# Generated by Fabric setup task', file=of)
        print(file=of)
        print(
            'from {{ project_name }}.config.{} import *'.format(target),
            file=of
        )
        print(linesep, file=of)
        for k, v in settings.iteritems():
            print("{} = '{}'".format(k, v), file=of)


def generate_settings():
    "Generate {{ project_name }}/settings.py"
    target = 'local'
    settings = OrderedDict()
    settings['SECRET_KEY'] = get_random_string(54)
    settings['DATABASES__DEFAULT__PASSWORD'] = getpass('PostgreSQL Password: ')
    settings['POSTMARK_API_KEY'] = getpass('Postmark API Key: ')
    write_settings(LOCAL_SETTINGS, target, settings)
    print(green('{} generated'.format(LOCAL_SETTINGS)))


def generate_virtualenvwrapper_hooks():
    "Generate $VIRTUAL_ENV/bin/ hooks"
    ve_bin = join(VIRTUAL_ENV, 'bin')
    template_dir = join(PACKAGE_ROOT, 'deploy', 'templates')
    context = {
        'local_settings': LOCAL_SETTINGS,
        'project_name': '{{ project_name }}',
    }
    for hook in ('postactivate', 'postdeactivate'):
        with open(join(ve_bin, hook), 'w+') as of:
            of.write(render_template(join(template_dir, hook), context))


@task()
def local_setup():
    "Generate {{ project_name }}/settings.py and $VIRTUAL_ENV/bin/ hooks"
    generate_settings()
    generate_virtualenvwrapper_hooks()
